name: ddnsb0t
on:
  push:
    paths-ignore:
    - "function/**"
    - ".github/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Download go modules
      run: go mod download

    - name: Verify go modules
      run: go mod verify

    - name: Build
      run: go build -v .
